### ISSUE TITLE
Manifest file generation

### ISSUE THREAD

**Issue by tumidi** [innodoc/innoconv#31]
In GitLab by @ramsesoriginal on Sep 11, 2018, 24:26

A `manifest.yaml` is read that is converted to `manifest.json` and holds metadata for the course (single file for all languages in project root dir).

Metadata could include:

* Supported Languages
* Course Title in each language
* TOC
* Logo
* Keywords
* PDF generation
* License
* About
* Institution
* Custom pages
* API endpoint (Auth, exercise records)

```yaml
title_de: Titel
title_en: Title
logo_de: "logo_en.svg",
logo_en: "logo_de.svg",
author:
  - Steven Smith
  - Michel Meyers
keywords: [nothing, nothingness]
custom_content:
  - [...]
```

See also: innodoc/innodoc-webapp#32, innodoc/innodoc-webapp#44, innodoc/innoconv-mintmod#4
